name: "Decky"
description: "The Decky CLI"
author: "SteamDeckHomebrew"
inputs:
  args:
    description: "Arguments to pass to the Decky CLI"
    required: true
runs:
  using: "docker"
  image: "docker://kaze404/decky"
  args:
    - ${{ inputs.args }}
